# Generated by Django 3.1 on 2020-08-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0004_team_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
