# Generated by Django 3.1 on 2020-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars/'),
        ),
    ]
