# Generated by Django 3.1 on 2020-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0007_auto_20200923_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='paris/static/paris/images/avatars/default.png', null=True, upload_to='paris/static/paris/images/avatars/'),
        ),
    ]
