# Generated by Django 3.1 on 2020-09-24 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paris', '0008_auto_20200923_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetRoom_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AD', 'Administrator'), ('P', 'Participant')], default='P', max_length=2)),
                ('BetRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paris.betroom')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paris.profile')),
            ],
        ),
        migrations.AddField(
            model_name='betroom',
            name='users',
            field=models.ManyToManyField(related_name='_betroom_users_+', through='paris.BetRoom_Profile', to='paris.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rooms',
            field=models.ManyToManyField(related_name='_profile_rooms_+', through='paris.BetRoom_Profile', to='paris.BetRoom'),
        ),
    ]
